name: CI

on:
  push:
    paths:
      - 'project2/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'project2/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello World"